import React from "react";

// Uzbek Latin translations
const translations = {
  // Login page
  login: "Tizimga kirish",
  username: "Foydalanuvchi nomi",
  password: "Parol",
  forgotPassword: "Parolni unutdingizmi?",
  signIn: "Kirish",
  // Dashboard
  dashboard: "Boshqaruv paneli",
  dailySales: "Kunlik sotuvlar",
  monthlySales: "Oylik sotuvlar",
  registerBalance: "Kassa balansi",
  lowStock: "Kam qoldiq",
  // Navigation
  pos: "Sotuv",
  products: "Mahsulotlar",
  type: "Turi",
  priceSellUzs: "Narxi (Sotish/UZS)",
  stockInfo: "Ombor/Info",
  android: "Android",
  iphone: "iPhone",
  inventory: "Ombor",
  reports: "Hisobotlar",
  installments: "Muddatli to'lovlar",
  // settings: "Sozlamalar",
  logout: "Chiqish",
  // POS
  cart: "Savat",
  scanBarcode: "Shtrix kodni skanerlang",
  product: "Mahsulot",
  price: "Narxi",
  quantity: "Soni",
  total: "Jami",
  paymentMethod: "To'lov usuli",
  Naqd: "Naqd",
  card: "Plastik",
  mixed: "Aralash",
  credit: "Nasiya",
  installment: "Muddatli to'lov",
  // General
  cancel: "Bekor qilish",
  save: "Saqlash",
  create: "Yaratish",
  edit: "Tahrirlash",
  delete: "O'chirish",
  search: "Qidirish",
  uzs: "so'm",
  sales: "sotuvlar",
  day: "kun",
  available: "mavjud",
  addToCart: "Savatga qo'shish",
  noProductsFound: "Mahsulotlar topilmadi",
  cartEmpty: "Savat bo'sh",
  employees: "Hodimlar",
  checkout: "Buyurtma berish",
  // Superadmin translations
  superadmin: "Bosh admin",
  stores: "Do'konlar",
  subscriptions: "Obunalar",
  payments: "To'lovlar",
  storeOwner: "Do'kon egasi",
  status: "Holati",
  active: "Faol",
  expired: "Muddati tugagan",
  blocked: "Bloklangan",
  subscriptionType: "Obuna turi",
  validUntil: "Amal qilish muddati",
  createStore: "Do'kon yaratish",
  storeName: "Do'kon nomi",
  ownerName: "Egasining ismi",
  ownerPhone: "Telefon raqami",
  features: "Imkoniyatlar",
  extend: "Muddatni uzaytirish",
  block: "Bloklash",
  unblock: "Blokdan chiqarish",
  paymentStatus: "To'lov holati",
  pending: "Kutilmoqda",
  approved: "Tasdiqlangan",
  rejected: "Rad etilgan",
  amount: "Summa",
  paymentDate: "To'lov sanasi",
  receipt: "Chek",
  viewImage: "Rasmni ko'rish",
  approve: "Tasdiqlash",
  reject: "Rad etish",
  actions: "Amallar",
  users: "Foydalanuvchilar",
  list: "Ro'yxat",
  current_stock: "Joriy zaxira",
  remaining: "Qolgan",
  store_information: "Do'kon ma'lumotlari",
  sales_report: "Sotuvlar hisoboti",
  inventory_report: "Ombor hisoboti",
  inventory_status: "Ombor holati",
  report: "hisobot",
  no_data: "Ma'lumot yo'q",
  customer: "Mijoz",
  add: "Qo'shish",
  name: "Nomi",
  date: "Sana",
  payment_method: "To'lov usuli",
  store: "Do'kon",
  information: "Ma'lumot",
  subscription: "Obuna",
  // AddProductDialog translations
  addProduct: "Mahsulot qo'shish",
  addProductDescription: "Yangi mahsulot qo'shish uchun ma'lumotlarni to'ldiring",
  barcode: "Shtrix kod",
  category: "Kategoriya",
  priceUzs: "Narxi (so'm)",
  priceUsd: "Narxi (dollar)",
  addAndroid: "Android",
  addAndroidDescription: "Yangi Android qurilma qo'shish uchun ma'lumotlarni to'ldiring",
  androidAdded: "Android qurilma muvaffaqiyatli qo'shildi",
  addIPhone: "iPhone",
  addIPhoneDescription: "Yangi iPhone qo'shish uchun ma'lumotlarni to'ldiring",
  purchasePrice: "Olingan narxi",
  sellingPriceHeader: "Sotish Narxi",
  capacity: "Hajmi",
  region: "Seriyasi/Region",
  capacityAndroidLabel: "Sig'imi",
  capacityValueLabel: "Sig'imi",
  capacityUnitLabel: "Yomkost",
  sellingPrice: "Sotiladigan narxi",
  color: "Rangi",
  iPhoneAdded: "iPhone muvaffaqiyatli qo'shildi",
  "e.g.": "Masalan:",
  batteryHealthLabel: "Batareya holati (%)",
  // Other translations
  totalAmount: "Umumiy summa",
  remainingAmount: "Qolgan summa",
  nextPayment: "Keyingi to'lov",
  view: "Ko'rish",
  completed: "Tugallangan",
  overdue: "Muddati o'tgan",
  purchaseDateLabel: "Olingan sana",
};

// Translation function
export const t = (key) => {
  return translations[key] || key; // Return the Uzbek Latin translation or the key if not found
};